image: gitpod/workspace-full

tasks:
  - name: Ollama Install and start service
    before: echo "Hi from Terminal 2"
    init: curl -fsSL https://ollama.com/install.sh  | sh
    command: ollama serve && ollama pull nomic-embed-text && ollama run llama3.2  
  
  - name: install and set up the environment  
    init: pip install crewai && pip install crewai-tools && pip install langchain-community && pip install python-dotenv && pip install --upgrade pip && pip install langchain-ollama && pip install streamlit && pip install unstructured

 


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
