image: gitpod/workspace-full

tasks:
  - name: Ollama Install and start service
    before: echo "Hi from Terminal 2"
    init: curl -fsSL https://ollama.com/install.sh  | sh
    command: ollama serve 
  
  - name: install and set up the environment  
    init: pip install gradio && pip install crewai && pip install creai[tools] && pip install ollama && pip install python-dotenv && pip install --upgrade pip

 


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
